const MemoryStrategy = require('../src/strategies/Memory')

module.exports = new MemoryStrategy()

// --- BELOW AUTOMATICALLY GENERATED BY ES-MIGRATE ---
// The version of the db this commit depends on
module.exports.version = '19920524010205-version-p-test-3'
